<?php
/**
 * Storage Path Configuration
 * PHP 8.5 - Using constants for path management
 *
 * Location: Y:\lib\storage\StorageConfig.php
 *
 * IMPORTANT: This file is OUTSIDE storage directory.
 * Storage directory contains ONLY data, no executable PHP code.
 */

declare(strict_types=1);

// Base storage directory
if (!defined('STORAGE_ROOT')) {
    define('STORAGE_ROOT', dirname(__DIR__, 2) . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR);
}

// Application Paths
define('STORAGE_APP', STORAGE_ROOT . 'app' . DIRECTORY_SEPARATOR);
define('STORAGE_CACHE', STORAGE_APP . 'cache' . DIRECTORY_SEPARATOR);
define('STORAGE_LOGS', STORAGE_APP . 'logs' . DIRECTORY_SEPARATOR);
define('STORAGE_TMP', STORAGE_APP . 'tmp' . DIRECTORY_SEPARATOR);

// Protected Secrets Path
define('STORAGE_PROTECTED', STORAGE_ROOT . 'protected' . DIRECTORY_SEPARATOR);
define('STORAGE_API_KEYS', STORAGE_PROTECTED . 'api-keys' . DIRECTORY_SEPARATOR);
define('STORAGE_CERTIFICATES', STORAGE_PROTECTED . 'certificates' . DIRECTORY_SEPARATOR);
define('STORAGE_ENCRYPTION', STORAGE_PROTECTED . 'encryption' . DIRECTORY_SEPARATOR);

// Upload Paths
define('STORAGE_UPLOADS', STORAGE_ROOT . 'uploads' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_PROPERTIES', STORAGE_UPLOADS . 'properties' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_IMAGES', STORAGE_UPLOADS_PROPERTIES . 'images' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_BLUEPRINTS', STORAGE_UPLOADS_PROPERTIES . 'blueprints' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_MEDIA', STORAGE_UPLOADS . 'media' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_MEDIA_TVDISPLAY', STORAGE_UPLOADS_MEDIA . 'tvdisplay' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_DOCUMENTS', STORAGE_UPLOADS . 'documents' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_DOCUMENTS_REPORTS', STORAGE_UPLOADS_DOCUMENTS . 'reports' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_DOCUMENTS_REPORTS_PDF', STORAGE_UPLOADS_DOCUMENTS_REPORTS . 'pdf' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_DOCUMENTS_TEMPLATES', STORAGE_UPLOADS_DOCUMENTS . 'templates' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_DOCUMENTS_TEMPLATES_WORD', STORAGE_UPLOADS_DOCUMENTS_TEMPLATES . 'word' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_DOCUMENTS_TEMPLATES_ORIGINAL', STORAGE_UPLOADS_DOCUMENTS_TEMPLATES . 'original' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_COMMUNICATIONS', STORAGE_UPLOADS . 'communications' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_COMMUNICATIONS_MESSAGING', STORAGE_UPLOADS_COMMUNICATIONS . 'messaging' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_COMMUNICATIONS_EMAIL', STORAGE_UPLOADS_COMMUNICATIONS . 'email' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_COMMUNICATIONS_EMAIL_DATA', STORAGE_UPLOADS_COMMUNICATIONS_EMAIL . 'maildata' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_AI', STORAGE_UPLOADS . 'ai' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_AI_IMAGES', STORAGE_UPLOADS_AI . 'images' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_AI_AUDIO', STORAGE_UPLOADS_AI . 'audio' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_WHATSAPP', STORAGE_UPLOADS . 'whatsapp' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_WHATSAPP_FILES', STORAGE_UPLOADS_WHATSAPP . 'files' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_SLIDESHOW', STORAGE_UPLOADS . 'slideshow' . DIRECTORY_SEPARATOR);
define('STORAGE_UPLOADS_MOKHATAT', STORAGE_UPLOADS . 'mokhatat' . DIRECTORY_SEPARATOR);

// Generated Paths
define('STORAGE_GENERATED', STORAGE_ROOT . 'generated' . DIRECTORY_SEPARATOR);
define('STORAGE_QR_CODES', STORAGE_GENERATED . 'qr-codes' . DIRECTORY_SEPARATOR);
define('STORAGE_THUMBNAILS', STORAGE_GENERATED . 'thumbnails' . DIRECTORY_SEPARATOR);

// Backup Paths
define('STORAGE_BACKUPS', STORAGE_ROOT . 'backups' . DIRECTORY_SEPARATOR);
define('STORAGE_BACKUPS_DB', STORAGE_BACKUPS . 'database' . DIRECTORY_SEPARATOR);

// Framework Paths
define('STORAGE_FRAMEWORK', STORAGE_ROOT . 'framework' . DIRECTORY_SEPARATOR);
define('STORAGE_FRAMEWORK_FILE_MANAGEMENT', STORAGE_FRAMEWORK . 'file-management' . DIRECTORY_SEPARATOR);
define('STORAGE_FRAMEWORK_FILE_MANAGEMENT_UPLOADS', STORAGE_FRAMEWORK_FILE_MANAGEMENT . 'uploads' . DIRECTORY_SEPARATOR);
define('STORAGE_FRAMEWORK_FILE_MANAGEMENT_CACHE', STORAGE_FRAMEWORK_FILE_MANAGEMENT . 'cache' . DIRECTORY_SEPARATOR);
define('STORAGE_FRAMEWORK_FILE_MANAGEMENT_LOGS', STORAGE_FRAMEWORK_FILE_MANAGEMENT . 'logs' . DIRECTORY_SEPARATOR);

// Initialize critical directories if they don't exist
$critical_dirs = [
    STORAGE_APP,
    STORAGE_CACHE,
    STORAGE_LOGS,
    STORAGE_TMP,
    STORAGE_UPLOADS,
    STORAGE_GENERATED,
    STORAGE_PROTECTED,
    STORAGE_FRAMEWORK,
];

foreach ($critical_dirs as $dir) {
    if (!is_dir($dir)) {
        @mkdir($dir, 0755, true);
    }
}
