serverAddr = "147.93.131.45"
serverPort = 7000

auth.method = "token"
auth.token = "{TOKEN}"

log.to = "C:/saudiakar-erp/aso/frp/log/frpc.log"
log.level = "info"
log.maxDays = 7


[[proxies]]

# Unique name per client (no spaces)
name = "{SERIAL_CODE}"

# Use http type for subdomain-based routing
type = "http"

# The local web server address on this PC
localIP = "127.0.0.1"
localPort = 9009



# The subdomain prefix for this customer
# Result: SUBDOMAIN.ourdomain.com
subdomain = "{SERIAL_CODE}"